### ISSUE TITLE
Await Callbacks—Race Condition

### ISSUE THREAD

**Issue by MANTENN** [poppinss/oauth-client#2]
### Package version

adonis@0.9.0

### Describe the bug

Currently when attempting to utilize the request context, because its asynchronous, the context from the request never gets attached. 

I made a few changes in a fork to accomodate these changes: https://github.com/MANTENN/oauth-client. However, I am looking through the rest of the code where it may not handle asynchronous conditions.

**Comment by thetutlage** [comment]
The issue is quite vague. Unfortunately, I cannot provide much help without looking at some code. Please, reopen if you can provide enough information to reproduce the issue
